# Generated by Django 4.0.4 on 2022-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cosinesimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120)),
                ('title', models.TextField()),
                ('score', models.TextField()),
                ('angle', models.TimeField()),
            ],
        ),
    ]
